### ISSUE TITLE
Microsite QA

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#112]

**Comment by mmmavis** [comment]
Video doesn't play on my FF 43.0.4 on OS X El Capitan 10.11.2  It stays like this after I clicked on the play button.
![fireshot capture 36 - mozilla advocacy - https___lit-mountain-52009 herokuapp com_encrypt_](https://cloud.githubusercontent.com/assets/2896608/12934093/ff7cbe50-cf40-11e5-9b0b-4c2615751952.png)
This can also be reproduced on the v2, v3 site.

**Comment by cadecairos** [comment]
On Firefox for Android, the after video modal for the first link appears on the top of the screen, leaving plenty of space below. Might be worth centering it.

Alan note: I've adjusted behavior for modals on mobile/desktop.

**Comment by mmmavis** [comment]
<img width="1440" alt="screen shot 2016-02-09 at 3 28 06 pm" src="https://cloud.githubusercontent.com/assets/2896608/12934211/c60739e2-cf41-11e5-91da-916293ebf048.png">

Dialog bubble got cut off on Chrome v48.0.2564.103 on OS X El Capitan 10.11.2.

**Comment by mmmavis** [comment]
Chrome v48.0.2564.103 on OS X El Capitan 10.11.2.
(Not sure if it's the same on FF as I can't get the video to play on FF)

https://lit-mountain-52009.herokuapp.com/encrypt/

the 3 social share buttons are not hyperlinked :sweat_smile: 

<img width="1440" alt="screen shot 2016-02-09 at 3 36 20 pm" src="https://cloud.githubusercontent.com/assets/2896608/12934371/e7aa7f72-cf42-11e5-9451-ea45a25358ae.png">

**Comment by mmmavis** [comment]
same issue as above: the 3 social share buttons are not hyperlinked 

<img width="1004" alt="screen shot 2016-02-09 at 3 40 20 pm" src="https://cloud.githubusercontent.com/assets/2896608/12934450/7aa9df7a-cf43-11e5-971e-b28c34721b8b.png">

**Comment by alanmoo** [comment]
Oops, forgot to mention that social buttons are still in progress, @mmmavis 😬

**Comment by lovegushwa** [comment]
@alanmoo just posted QA in redpen. 
https://redpen.io/uj0aafc47202304b06

Alan note: done

**Comment by alanmoo** [comment]
I can't reproduce the Firefox not playing video issue, @mmmavis. Anyone else getting that?

**Comment by mmmavis** [comment]
> I can't reproduce the Firefox not playing video issue, @mmmavis. Anyone else getting that?

@alanmoo 
Maybe I forgot to update a plugin or something :grimacing: Private Mode doesn't seem to solve the problem either so it shouldn't be related to any FF addons that I've installed on my machine

**Comment by mmmavis** [comment]
@alanmoo oops sorry for the false alarm!!!!  It's my Adblock Plus!!!  It was still running on Private Mode. Disabling it and restarting FF seem to solve the problem. :smile:

**Comment by simonwex** [comment]
https://github.com/MozillaFoundation/encryption_campaign/issues/113

**Comment by stephaniemcv** [comment]
PRIORITY 2
Browser: Firefox
Windows 8
Landing Page version 2 - 
If you signup using the form at the top, there's no confirmation unless you scroll down to the blue Join box and it says Thank you

Alan note: I've changed the behavior of submissions so the text changes on the button and then the modal fades away. In addition, the bottom "sign up" button still becomes "thank you" as described here

**Comment by stephaniemcv** [comment]
Mozilla logos (top left and bottom center) are not linked

Alan note: not addressed. They go to mozilla.org?

**Comment by valianttry** [comment]
PRIORITY 1
iOS
~~You should be able to click outside the Theater mode field and share. The video should pause. Right now you can click outside theater mode but nothing happens.~~

**Comment by shaghdoosti** [comment]
![screen shot 2016-02-09 at 5 42 30 pm](https://cloud.githubusercontent.com/assets/13626384/12936518/4080c3ca-cf54-11e5-9036-6f220ab2676b.png)

Is this the right default text? @KevZawacki

**Comment by shaghdoosti** [comment]
Headline: Check out this awesome video
Description: Join the movement for online privacy

**Comment by shaghdoosti** [comment]
![screen shot 2016-02-09 at 5 46 07 pm](https://cloud.githubusercontent.com/assets/13626384/12936575/b09f1670-cf54-11e5-8ef6-1978bd89f7ee.png)

Can we add -- @mozilla to the end of the twitter share plz?

**Comment by alanmoo** [comment]
@stephaniemcv where should those link to, mozilla.org?

**Comment by HPaulJohnson** [comment]
+1 to @shaghdoosti suggested edits for Facebook share. It looks like the Facebook pop-up still shows the old text but what actually gets posted to my wall has been updated with new copy?

Also, the email capture modal after the video plays doesn't do anything when I click "sign up." Happens in both FF and Chrome.

**Comment by alanmoo** [comment]
Fixes for the theater mode ( @valianttry ) and sign up confirmation ( @HPaulJohnson and @stephaniemcv ) are pending a review from Ali either tonight or first thing in the morning, and then they'll go live. Hat tip to @simonwex for uploading the correct videos to the CDN, and those are being referenced now in production.

I'm going home now, but first things for me to fix tomorrow
- [x] The encrypt text covering the video
- [x] modal positioning after the video plays
- [x] Jordan's redpen changes (above, some of which have been addressed already)
- [x] The animated Encrypt text. 

I'm planning on addressing them in that order, but someone let me know if that should change.

**Comment by HPaulJohnson** [comment]
Screen shots for social share issue that I'm still seeing. 

Clicking Facebook share brings up this page with old text: https://www.evernote.com/shard/s46/sh/bdb4f18f-5086-42ba-8e1e-3b74cb9dff6e/394ef3324e89d5d3a1aa50a9a01b0633

Once posted to Facebook the actual shared content has the correct, updated copy: https://www.evernote.com/shard/s46/sh/bc6380d8-82bf-4404-8480-a1362ba52abb/1ef288281615750910fae36af9c04368

**Comment by lovegushwa** [comment]
@alanmoo when playing a video, you should be able to click out of the theater mode view or CTA modal. In both cases let's reload page so it looks like this:

(Page should like like you just landed on the site  for v1 and v2)
<img width="1645" alt="screen shot 2016-02-09 at 7 30 43 pm" src="https://cloud.githubusercontent.com/assets/12228435/12938032/a0b06048-cf63-11e5-9641-2aa52edee774.png">

Alan note: this should be addressed. Please reevaluate.

**Comment by stephaniemcv** [comment]
@alanmoo 
Yes, the signup on mozilla.org, at the bottom of the page, is configured correctly. And info passed through there is triggered a confirmation email. The signup on the landing page is not passing the info to Basket to trigger the email.

Alan note: I believe this is addressed now

**Comment by valianttry** [comment]
@alanmoo can you update here what of the above bugs are fixed / still pending? cc @alicoding

**Comment by alanmoo** [comment]
@valianttry I've edited all the comments relevant to me with notes.

**Comment by valianttry** [comment]
@alanmoo :clap: :+1:

**Comment by valianttry** [comment]
We need to add a donate link to the bottom of the Microsite (P1) @lovegushwa The icon can be a heart.

![mozilla_advocacy](https://cloud.githubusercontent.com/assets/9830371/12995876/d8cf60be-d0df-11e5-9338-2b20f4352cc1.png)

**Comment by alanmoo** [comment]
https://donate.mozilla.org/ ? I can whip that together now, no need for a comp if it's simply a heart icon styled like the rest of them. Does it have to be on the right or can it be in the middle of the other elements?

**Comment by lovegushwa** [comment]
Hi @alanmoo 
It should be on the right, also we need to make the donate icon red and not in a circle (the same red your using on site.)

Here is a SVG red heart, you can also use font-awesome equivalent if needed.
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvcWkwdEhiUVJJd2M/view?usp=sharing

<img width="1199" alt="screen shot 2016-02-12 at 10 51 08 am" src="https://cloud.githubusercontent.com/assets/12228435/13016938/9783f7ae-d176-11e5-95f2-2d335c64edae.png">

**Comment by alanmoo** [comment]
Should this go on the main advocacy site too? It's all the same component, so it would be easy. @lovegushwa @valianttry

**Comment by lovegushwa** [comment]
Italic across the site looks like a heaver weight than the body copy. Can you make it "book italic"?

<img width="384" alt="screen shot 2016-02-12 at 10 57 02 am" src="https://cloud.githubusercontent.com/assets/12228435/13017382/c3457d48-d178-11e5-8a77-fd63ac61c028.png">

Alan note: PR submitted. Coming soon.

**Comment by alanmoo** [comment]
This is getting hard to manage, let's make any further issues a new github issue so that they're easier to track. Just give them a dev label and assign to me.

**Comment by alanmoo** [comment]
I believe all of the above are fixed, except for the encrypt text animation, which I'm working on now (#126).
